resource_manifest_version '44febabe-d386-4d18-afbe-5e627f4af937'
server_script 'server.lua'
client_script 'client.lua'
author 'InfiniteTurbo/Turbo Modifications'
title 'BE - Chat Commands'
description 'Basic Essentials Chat Commands'
version '1.0.0'
